server:
  port: 8855
  servlet:
    context-path: /
spring:
  application:
    name: jdprovider
  datasource:
    url: jdbc:mysql://72.19.12.227:3339/lihao?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: lihao
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
  rabbitmq:
    username: lihao
    password: lihao
    addresses: 72.19.12.227:5672
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  redis:
    host: 72.19.12.227
    port: 6379
    password: lihao
    database: 0
    timeout: 25000
    lettuce:
      pool:
        max-wait: -1
        max-active: 50
        max-idle: 10
        min-idle: 0
      shutdown-timeout: 5000
mybatis:
  type-aliases-package: com.demo.ai.entity
  mapper-locations: classpath:mapper/*.xml